# google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - categories.md
  - tags.md
  - about.md

footer: 'contact me on <a href="https://twitter.com/_mini_pingu_">twitter</a> | <a href="https://t.me//MiniPingu">telegram</a>'

style: dark

plugins:
  - jekyll-seo-tag
