# Example Site settings

google_analytics: UA-NNNNNNNN-N

header_pages:
  - pages/index.md
  - pages/posts.md
  - pages/todo.md
  - pages/log.md
  - pages/about.md

footer: 'Currently: Being a Javascript Full-Stack Developer...'

style: dark

plugins:
  - jekyll-seo-tag

remote_theme: b2a3e8/jekyll-theme-console

