title: "Mini-Pingu"
lang: "en"
description: "Playground of _Mini_Pingu_"
baseurl: "/"
url: "https://mini-pingu.github.io"

header_pages:
  - pages/index.md
  - pages/categories.md
  - pages/archive.md
  - pages/about.md

style: hacker

footer: '<a href="https://twitter.com/SokaOrochi">Soka Orochi</a>'

listen_for_clients_preferred_style: false

plugins:
  - jekyll-seo-tag
