# google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - categories.md
  - tags.md
  - about.md

footer: 'contact me on <a href="https://twitter.com/_mini_pingu_">twitter</a>'

style: dark

plugins:
  - jekyll-seo-tag

kramdown:
  parse_block_html: true