google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - categories.md
  - tags.md
  - about.md

footer: 'follow me on <a href="https://twitter.com/_mini_pingu_">twitter</a>'

style: dark # dark (default) or light
# listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
